# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93098e7e1caaf5b87a6e6eff8acb351dc5a7a8ff9966dabfbc09370ada806ac44e71838f260faf5c5e594703cd22495e91d0fdd536ab5073849587476f9f4be0

test:
  secret_key_base: 3ded95d9d4ade8e5daa8225ff721472f5423a4ed66c958873e50c52c0d82f9e53575fe0ca17c2f58b8ae597d78d855a656047393ec7940925e686f4bfd20d042

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
